server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
